excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://indocipherable.github.io
title: Indocipherable
tagline: Kemerdekaan Ruang Privat
description: Blog berbahasa Indonesia berisi berita, tutorial dan esai seputar hak individu atas privasi dan keleluasaan berekspresi di era digital.
paginate: 5
